Added new Checks
blst-security/cherrybomb pull request #10
Opened 2022-02-16 16:24 UTC by H31S3nb3rg-0x00

Check for get permissions  ( has to be only read)
Check for post permissions ( has to be only read and write)
Check for put permissions ( has to be only write)

2022-02-26 11:22 UTC, GuyL99 requested changes
We'll revisit it later next week

2022-02-26 11:22 UTC, GuyL99 commented on swagger/src/scan/checks.rs
> +    (CheckGetPermissions, check_get_permissions, "GET PERMISSIONS", "Checks for correct permissions for get requests"),
We may need to merge those 3 checks into a single check with 3 alerts

2022-02-27 13:57 UTC, H31S3nb3rg-0x00 commented on swagger/src/scan/passive/additional_checks.rs
> +                        Some(x) => {
How do you suggest to name schemes?

2022-02-27 13:58 UTC, H31S3nb3rg-0x00 commented
I would happy to revisit my code together in order to apply changes

2022-03-23 07:01 UTC, merged