Tls support
blst-security/cherrybomb pull request #118
Opened 2023-02-08 17:23 UTC by DeliciousBounty

Hello 
This Pull request add support for tls errors according to the issue #94 .
The ignore parameter is passed trough all active checks. 
I changed http_client , req,  macro, additional_checks,..
I am here for any questions :)

2023-02-13 10:59 UTC, GuyL99 requested changes

2023-02-13 10:59 UTC, GuyL99 commented on Cargo.toml
> +cherrybomb-engine = {path = "cherrybomb-engine"}
path

2023-02-13 10:59 UTC, GuyL99 commented on cherrybomb-engine/Cargo.toml
> +cherrybomb-oas = {path = "../cherrybomb-oas"}
path

2023-02-13 10:59 UTC, GuyL99 commented on cherrybomb-engine/src/scan/active/http_client/req.rs
> +            .danger_accept_invalid_certs(self.ignore_tls_errors)
Are you sure that the boolean matches? I mean will it get the desired outcome or is it the opposite?

2023-02-13 10:59 UTC, GuyL99 commented on src/main.rs
> +        dbg!(&value);
dbg!@!!

2023-02-19 15:21 UTC, closed without merging

2023-02-19 15:22 UTC, DeliciousBounty commented
I am opening a newer