Exclude include
blst-security/cherrybomb pull request #134
Opened 2023-07-18 18:39 UTC by DeliciousBounty

This PR solved the following issue: #78  ( Users can have now the possibility to disable specific checks).
Based on a previous PR but added the possibility to passive include, active include.
In addition I removed the profile intrusive to active.

2023-07-19 10:28 UTC, GuyL99 requested changes

2023-07-19 10:28 UTC, GuyL99 commented on cherrybomb-engine/Cargo.toml
> +cherrybomb-oas={path = "../cherrybomb-oas"}
crates.io version needed

2023-07-19 10:28 UTC, GuyL99 commented on cherrybomb-engine/src/lib.rs
> +}
checks.iter().filter_map(|check| if confuig).collect()

2023-07-19 10:36 UTC, GuyL99 commented on cherrybomb-engine/src/lib.rs
> +}
put in config.rs in cherrybomb engine

2023-07-20 16:57 UTC, GuyL99 approved these changes
looks much better now

2023-08-16 00:36 UTC, jayvdb commented
@DeliciousBounty , this branch now has conflicts

2023-09-03 11:01 UTC, merged